/*
 * flux_algebra — HarmonicRing operations, group theory for harmony,
 *                tuning field arithmetic
 *
 * C99 port of the Python flux-algebra library.
 * Ring/group operations on pitch classes, modular arithmetic, interval vectors.
 */

#include "flux_algebra.h"
#include <math.h>
#include <stdlib.h>
#include <string.h>

/* ─── HarmonicRing ─────────────────────────────────────────── */

void fa_harmonic_ring_init(FaHarmonicRing *hr, int modulus)
{
    hr->modulus = (modulus < 1) ? 12 : modulus;
}

int fa_add(const FaHarmonicRing *hr, int a, int b)
{
    return ((a % hr->modulus) + (b % hr->modulus) + hr->modulus) % hr->modulus;
}

int fa_subtract(const FaHarmonicRing *hr, int a, int b)
{
    return ((a % hr->modulus) - (b % hr->modulus) + hr->modulus) % hr->modulus;
}

int fa_multiply(const FaHarmonicRing *hr, int a, int b)
{
    long long la = a, lb = b, lm = hr->modulus;
    return (int)(((la % lm) * (lb % lm) % lm + lm) % lm);
}

int fa_negate(const FaHarmonicRing *hr, int a)
{
    return ((-(a % hr->modulus)) + hr->modulus) % hr->modulus;
}

int fa_invert(const FaHarmonicRing *hr, int a, int n)
{
    return ((n - a) % hr->modulus + hr->modulus) % hr->modulus;
}

int fa_transpose(const FaHarmonicRing *hr, int pc, int interval)
{
    return ((pc + interval) % hr->modulus + hr->modulus) % hr->modulus;
}

int fa_units(const FaHarmonicRing *hr, int *out, int max_out)
{
    int count = 0;
    for (int k = 1; k < hr->modulus && count < max_out; k++) {
        if (fa_gcd(k, hr->modulus) == 1)
            out[count++] = k;
    }
    return count;
}

/* ─── Ideals ───────────────────────────────────────────────── */

int fa_all_ideals(const FaHarmonicRing *hr, FaIdeal *out, int max_out)
{
    int count = 0;
    for (int d = 1; d <= hr->modulus && count < max_out; d++) {
        if (hr->modulus % d == 0) {
            int n = 0;
            for (int v = 0; v < hr->modulus && n < FA_MAX_ELEMENTS; v += d)
                out[count].elements[n++] = v;
            out[count].count = n;
            count++;
        }
    }
    /* Sort by size (smallest first) via simple insertion sort */
    for (int i = 1; i < count; i++) {
        FaIdeal tmp = out[i];
        int j = i;
        while (j > 0 && out[j-1].count > tmp.count) {
            out[j] = out[j-1];
            j--;
        }
        out[j] = tmp;
    }
    return count;
}

FaIdeal fa_ideal_generated_by(const FaHarmonicRing *hr,
                               const int *gens, int n_gens)
{
    /* Ideal generated by {g1,...,gk} in Z/nZ is the subgroup
       generated by gcd(g1,...,gk,n) */
    int g = hr->modulus;
    for (int i = 0; i < n_gens; i++) {
        int gi = gens[i] % hr->modulus;
        if (gi < 0) gi += hr->modulus;
        g = fa_gcd(g, gi);
    }
    FaIdeal ideal;
    ideal.count = 0;
    for (int v = 0; v < hr->modulus && ideal.count < FA_MAX_ELEMENTS; v += g)
        ideal.elements[ideal.count++] = v;
    return ideal;
}

int fa_interval_class(const FaHarmonicRing *hr, int a, int b)
{
    int diff = abs(a - b) % hr->modulus;
    int half = hr->modulus - diff;
    return (diff < half) ? diff : half;
}

int fa_pitch_class_set(const FaHarmonicRing *hr, const int *notes, int n,
                       int *out, int max_out)
{
    int seen[FA_MAX_ELEMENTS] = {0};
    int count = 0;
    for (int i = 0; i < n; i++) {
        int pc = ((notes[i] % hr->modulus) + hr->modulus) % hr->modulus;
        if (!seen[pc]) {
            seen[pc] = 1;
            if (count < max_out)
                out[count++] = pc;
        }
    }
    /* Sort */
    for (int i = 1; i < count; i++) {
        int tmp = out[i];
        int j = i;
        while (j > 0 && out[j-1] > tmp) {
            out[j] = out[j-1];
            j--;
        }
        out[j] = tmp;
    }
    return count;
}

/* ─── Prime form ───────────────────────────────────────────── */

static void sort_ints(int *a, int n)
{
    for (int i = 1; i < n; i++) {
        int tmp = a[i];
        int j = i;
        while (j > 0 && a[j-1] > tmp) {
            a[j] = a[j-1];
            j--;
        }
        a[j] = tmp;
    }
}

/* Generate all rotations of sorted pcs as a sequence of intervals from 0.
   Then find the most left-packed one (smallest span, then smallest intervals left-to-right). */
static void normal_order(const int *pcs_in, int n, int *out)
{
    if (n <= 1) { memcpy(out, pcs_in, n * sizeof(int)); return; }

    /* Start with sorted input */
    int pcs[FA_MAX_ELEMENTS];
    memcpy(pcs, pcs_in, n * sizeof(int));
    sort_ints(pcs, n);

    int best[FA_MAX_ELEMENTS];
    memcpy(best, pcs, n * sizeof(int));
    int best_span = pcs[n-1] - pcs[0];

    /* Try each rotation */
    for (int start = 0; start < n; start++) {
        int rot[FA_MAX_ELEMENTS];
        /* Build rotation: pcs[start], pcs[start+1], ..., pcs[n-1], pcs[0]+mod, ..., pcs[start-1]+mod */
        int idx = 0;
        for (int i = start; i < n; i++)
            rot[idx++] = pcs[i];
        int base = pcs[start];
        for (int i = 0; i < start; i++)
            rot[idx++] = pcs[i] + 12;  /* wrap around */

        /* Transpose so first = 0 */
        for (int i = 0; i < n; i++)
            rot[i] -= base;

        int span = rot[n-1];

        /* Compare: smaller span wins; if equal span, compare intervals left-to-right */
        int better = 0;
        if (span < best_span) better = 1;
        else if (span == best_span) {
            for (int i = 0; i < n; i++) {
                if (rot[i] < best[i]) { better = 1; break; }
                if (rot[i] > best[i]) break;
            }
        }

        if (better) {
            memcpy(best, rot, n * sizeof(int));
            best_span = span;
        }
    }

    memcpy(out, best, n * sizeof(int));
}

int fa_prime_form(const FaHarmonicRing *hr, const int *notes, int n,
                  int *out, int max_out)
{
    if (hr->modulus != 12) {
        /* Prime form only well-defined for 12-TET */
        int pc = fa_pitch_class_set(hr, notes, n, out, max_out);
        return pc;
    }

    /* Get sorted unique pitch classes */
    int pcs[FA_MAX_ELEMENTS];
    int np = fa_pitch_class_set(hr, notes, n, pcs, FA_MAX_ELEMENTS);
    if (np == 0) { return 0; }

    /* Normal order */
    int norm[FA_MAX_ELEMENTS];
    normal_order(pcs, np, norm);

    /* Already transposed to start at 0 by normal_order */
    int prime[FA_MAX_ELEMENTS];
    memcpy(prime, norm, np * sizeof(int));

    /* Inverted form: invert each interval around 0, get normal order */
    int inv[FA_MAX_ELEMENTS];
    for (int i = 0; i < np; i++)
        inv[i] = (12 - prime[i]) % 12;
    sort_ints(inv, np);
    int inv_norm[FA_MAX_ELEMENTS];
    normal_order(inv, np, inv_norm);

    /* Return the more left-packed one */
    int use_inv = 0;
    for (int i = 0; i < np - 1; i++) {
        int d_prime = prime[i+1] - prime[i];
        int d_inv   = inv_norm[i+1] - inv_norm[i];
        if (d_inv < d_prime) { use_inv = 1; break; }
        if (d_prime < d_inv) { break; }
    }

    int result_count = (np < max_out) ? np : max_out;
    memcpy(out, use_inv ? inv_norm : prime, result_count * sizeof(int));
    return result_count;
}

/* ─── IntervalRing ─────────────────────────────────────────── */

void fa_interval_ring_init(FaIntervalRing *ir,
                            const int *primes, int n_primes)
{
    ir->n_primes = (n_primes < 8) ? n_primes : 8;
    memcpy(ir->prime_limit, primes, ir->n_primes * sizeof(int));
}

void fa_interval_ring_default(FaIntervalRing *ir)
{
    int primes[] = {2, 3, 5, 7, 11};
    fa_interval_ring_init(ir, primes, 5);
}

static int64_t gcd64(int64_t a, int64_t b)
{
    if (a < 0) a = -a;
    if (b < 0) b = -b;
    while (b) { int64_t t = b; b = a % b; a = t; }
    return a;
}

static void reduce_frac(int64_t *num, int64_t *den)
{
    if (*den < 0) { *num = -*num; *den = -*den; }
    int64_t g = gcd64(*num, *den);
    if (g > 0) { *num /= g; *den /= g; }
}

void fa_ir_add(const FaIntervalRing *ir,
               int64_t a_num, int64_t a_den,
               int64_t b_num, int64_t b_den,
               int64_t *out_num, int64_t *out_den)
{
    (void)ir;
    *out_num = a_num * b_num;
    *out_den = a_den * b_den;
    reduce_frac(out_num, out_den);
}

void fa_ir_subtract(const FaIntervalRing *ir,
                    int64_t a_num, int64_t a_den,
                    int64_t b_num, int64_t b_den,
                    int64_t *out_num, int64_t *out_den)
{
    (void)ir;
    *out_num = a_num * b_den;
    *out_den = a_den * b_num;
    reduce_frac(out_num, out_den);
}

void fa_ir_multiply(const FaIntervalRing *ir,
                    int64_t a_num, int64_t a_den,
                    int64_t n,
                    int64_t *out_num, int64_t *out_den)
{
    (void)ir;
    if (n < 0) {
        /* For negative power: invert first */
        *out_num = a_den;
        *out_den = a_num;
        n = -n;
        reduce_frac(out_num, out_den);
        /* Now raise to |n| */
        int64_t base_num = *out_num, base_den = *out_den;
        *out_num = 1; *out_den = 1;
        for (int64_t i = 0; i < n; i++) {
            *out_num *= base_num;
            *out_den *= base_den;
        }
    } else {
        *out_num = 1; *out_den = 1;
        for (int64_t i = 0; i < n; i++) {
            *out_num *= a_num;
            *out_den *= a_den;
        }
    }
    reduce_frac(out_num, out_den);
}

void fa_ir_invert(int64_t num, int64_t den,
                  int64_t *out_num, int64_t *out_den)
{
    *out_num = den;
    *out_den = num;
    reduce_frac(out_num, out_den);
}

double fa_ir_cents(int64_t num, int64_t den)
{
    double ratio = (double)num / (double)den;
    return 1200.0 * log2(ratio);
}

/* ─── Group theory ─────────────────────────────────────────── */

int fa_gcd(int a, int b)
{
    if (a < 0) a = -a;
    if (b < 0) b = -b;
    while (b) { int t = b; b = a % b; a = t; }
    return a;
}

int fa_mod_inverse(int a, int m)
{
    a = ((a % m) + m) % m;
    for (int x = 1; x < m; x++) {
        if (((long long)a * x) % m == 1) return x;
    }
    return -1;  /* No inverse (not coprime) */
}

int fa_element_order(int a, int n)
{
    a = ((a % n) + n) % n;
    if (a == 0) return 1;
    int val = a;
    for (int k = 1; k <= n; k++) {
        if (val == 0) return k;
        val = (val + a) % n;
    }
    return n;
}

int fa_same_subgroup(int a, int b, int n)
{
    /* Two elements generate the same cyclic subgroup iff
       they have the same order and one is a power of the other */
    if (fa_element_order(a, n) != fa_element_order(b, n)) return 0;
    /* Check if b is a multiple of a mod n */
    for (int k = 1; k <= n; k++) {
        if (((long long)k * a) % n == b % n) return 1;
    }
    return 0;
}

/* ─── Interval vector ─────────────────────────────────────── */

void fa_interval_vector(const FaHarmonicRing *hr,
                        const int *pcs, int n,
                        int counts[7])
{
    memset(counts, 0, 7 * sizeof(int));
    for (int i = 0; i < n; i++) {
        for (int j = i + 1; j < n; j++) {
            int ic = fa_interval_class(hr, pcs[i], pcs[j]);
            if (ic < 7) counts[ic]++;
        }
    }
}
